import pygame, os
from const import screen_size
pygame.init()

pick_up_confirmation = [pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_1.png')), (screen_size, screen_size)),                                pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_2.png')), (screen_size, screen_size)),
 pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_3.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_4.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_5.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_6.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_7.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_8.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_9.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_10.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_11.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_12.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_13.png')), (screen_size, screen_size)),
 pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_14.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_15.png')), (screen_size, screen_size)),                         pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_16.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_17.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_18.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_19.png')), (screen_size, screen_size)),
pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/pick_up_confirmation', 'pick_up_20.png')), (screen_size, screen_size))]
wow = [pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'loop_1.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'loop_2.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'Wow_1.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'Wow_2.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'Wow_3.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'Wow_4.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'Wow_5.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'Wow_6.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/wow', 'Wow_7.png')), (screen_size, screen_size))]
got = [pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'loop_1.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'loop_2.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_1.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_2.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_3.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_4.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_5.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_6.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_7.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_8.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_9.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_10.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_11.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_12.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_13.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_14.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_15.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_16.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_17.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_18.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_19.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_20.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_21.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_22.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_23.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_24.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_25.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_26.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_27.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_28.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_29.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_30.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_31.png')), (screen_size, screen_size)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/pick_up_animation/you_got', 'You_got_32.png')), (screen_size, screen_size))]
stat = [pygame.transform.scale(pygame.image.load(os.path.join('assets/stat', 'Armour_New.png')),((screen_size/2),213)),
 pygame.transform.scale(pygame.image.load(os.path.join('assets/stat', 'Armour_old.png')),((screen_size/2),213)),
 pygame.transform.scale(pygame.image.load(os.path.join('assets/stat', 'weapon_new.png')),((screen_size/2),213)),
 pygame.transform.scale(pygame.image.load(os.path.join('assets/stat', 'weapon_old.png')),((screen_size/2),213))]
numbers = [pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '0.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '1.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '2.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '3.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '4.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '5.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '6.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '7.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '8.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', '9.png')),(34,48)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/number', 'period.png')),(34,48))]
gun_bro = [pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'loop_1.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'loop_2.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_1.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_2.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_3.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_4.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_5.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_6.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_7.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_8.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_9.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_10.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_11.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_12.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_13.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_14.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_15.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/Bro', 'bro_16.png')), (screen_size, 150))]
no_dig = [pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'loop_1.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'loop_2.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_1.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_2.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_3.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_4.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_5.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_6.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_7.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_8.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_9.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_10.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_11.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_12.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_13.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_14.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_15.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_16.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_17.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_18.png')), (screen_size, 150)),
   pygame.transform.scale(pygame.image.load(os.path.join('assets/got_gun/no more dig for you', 'no_more_dig_19.png')), (screen_size, 150)),]
identify = [pygame.transform.scale(pygame.image.load(os.path.join('assets/others', 'armour.png')), (250, 250)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/others', 'sword.png' )), (250, 250)),
           pygame.transform.scale(pygame.image.load(os.path.join('assets/others', 'gun.png' )), (750, 750))]
torch = [[pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'loop_1.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'loop_2.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_1.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_2.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_3.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_4.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_5.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_6.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_7.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_8.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_9.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_10.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_11.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_12.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_13.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_14.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_15.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_16.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_17.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_18.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_1', 'wow_19.png')), (screen_size, 150))],
  [pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'loop_1.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'loop_2.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_2.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_3.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_4.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_5.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_6.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_7.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_8.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_9.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_10.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_11.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_12.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_13.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_14.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_15.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_16.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_17.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_18.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_19.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_20.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_21.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_22.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_23.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_24.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_25.png')), (screen_size, 150)),
  pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/pick_up_2', 'wow_26.png')), (screen_size, 150)),]]
view = [pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'loop_1.png')),(screen_size, 150)),
        pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'loop_2.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_1.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_2.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_3.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_4.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_5.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_6.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_7.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_8.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_9.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_10.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_11.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_12.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_13.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_14.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_15.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_16.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_17.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_18.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_19.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_20.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_21.png')),(screen_size, 150)),
       pygame.transform.scale(pygame.image.load(os.path.join('assets/torch/view', 'view_22.png')),(screen_size, 150)),]
gun_got = [pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'loop_1.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'loop_2.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_2.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_3.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_4.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_5.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_6.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_7.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_8.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_9.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_10.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_11.png')), (screen_size, screen_size)),
          pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/gun_wow', 'gun_12.png')), (screen_size, screen_size)),]
gun_shock = [pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'loop_1.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'loop_2.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_0.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_1.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_2.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_3.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_4.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_5.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_6.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_7.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_9.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_10.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_11.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_12.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_13.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_14.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_15.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_16.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_17.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_18.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_19.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_20.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_21.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_22.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_23.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_24.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_25.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_26.png')),(screen_size, screen_size)),
            pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/shock', 'shocking_27.png')),(screen_size, screen_size))]
no_dig_2 = [pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'loop_1.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'loop_2.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_1.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_2.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_3.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_4.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_5.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_6.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_7.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_8.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_9.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_10.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_11.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_12.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_13.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_14.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_15.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_16.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_17.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_18.png')),(screen_size, screen_size)),
         pygame.transform.scale(pygame.image.load(os.path.join('assets/gun_get/no_dig', 'no_dig_19.png')),(screen_size, screen_size))]